-- Add ActivityAction values for admin-portal audit events (additive, non-destructive).
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'STAFF_CREATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'STAFF_UPDATED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'STAFF_STATUS_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'STAFF_PASSWORD_RESET';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LEAD_ASSIGNED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LEAD_UPDATED_DETAILS';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LEAD_ERASED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'DATA_EXPORTED';
