export const dynamic = "force-dynamic";

import Link from "next/link";

import { patientLeadsRepository } from "../../../../../shared/database";
import { patientLeadFiltersSchema } from "../../../../../shared/validations/patient-lead";

import { StatusPill } from "@/components/dashboard/status-pill";

export default async function LeadsPage({ searchParams }: { searchParams: Record<string, string | string[] | undefined> }) {
  const filters = patientLeadFiltersSchema.parse({
    q: searchParams.q,
    status: searchParams.status,
    urgency: searchParams.urgency,
    page: searchParams.page,
    pageSize: searchParams.pageSize,
  });

  const leads = await patientLeadsRepository.listLeads(filters);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-semibold tracking-tight text-white">Leads</h2>
        <p className="mt-2 text-sm text-slate-400">Search, filter, and manage patient leads generated by Vapi and n8n.</p>
      </div>

      <div className="overflow-hidden rounded-[1.75rem] border border-white/10 bg-white/5">
        <table className="min-w-full text-left text-sm text-slate-200">
          <thead className="bg-white/5 text-xs uppercase tracking-[0.18em] text-slate-400">
            <tr>
              <th className="px-6 py-4 font-medium">Patient Name</th>
              <th className="px-6 py-4 font-medium">Phone</th>
              <th className="px-6 py-4 font-medium">Email</th>
              <th className="px-6 py-4 font-medium">Reason For Visit</th>
              <th className="px-6 py-4 font-medium">Urgency</th>
              <th className="px-6 py-4 font-medium">Status</th>
              <th className="px-6 py-4 font-medium">Created At</th>
            </tr>
          </thead>
          <tbody>
            {leads.map((lead) => (
              <tr key={lead.id} className="border-t border-white/10 hover:bg-white/5">
                <td className="px-6 py-4 font-medium text-white">
                  <Link href={`/dashboard/leads/${lead.id}`} className="transition hover:text-sky-300">
                    {lead.patientName}
                  </Link>
                </td>
                <td className="px-6 py-4 text-slate-300">{lead.phone}</td>
                <td className="px-6 py-4 text-slate-300">{lead.email ?? "-"}</td>
                <td className="px-6 py-4 text-slate-300">{lead.reasonForVisit}</td>
                <td className="px-6 py-4"><StatusPill value={lead.urgency} /></td>
                <td className="px-6 py-4"><StatusPill value={lead.status} /></td>
                <td className="px-6 py-4 text-slate-400">{lead.createdAt.toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
