export const ACTIVITY_ACTIONS = [
  "LEAD_CREATED",
  "LEAD_UPDATED",
  "CONVERSATION_STARTED",
  "CONVERSATION_ENDED",
  "APPOINTMENT_CREATED",
  "APPOINTMENT_UPDATED",
  "STATUS_CHANGED",
] as const;
