export const dynamic = "force-dynamic";

import Link from "next/link";

import { patientLeadsRepository } from "@novadent/database";
import {
  EmptyState,
  PageHeader,
  Pagination,
  StatusBadge,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@novadent/ui";
import { patientLeadFiltersSchema } from "@novadent/validations";

import { ExportCsvButton } from "@/components/dashboard/export-csv-button";
import { LeadsFilterBar } from "@/components/dashboard/leads-filter-bar";
import { getStaffSessionFromCookies } from "@/lib/session";

export default async function LeadsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const resolvedSearchParams = await searchParams;
  const filters = patientLeadFiltersSchema.parse({
    q: resolvedSearchParams.q,
    status: resolvedSearchParams.status,
    urgency: resolvedSearchParams.urgency,
    page: resolvedSearchParams.page,
    pageSize: resolvedSearchParams.pageSize,
  });

  const [leads, totalItems, session] = await Promise.all([
    patientLeadsRepository.listLeads(filters),
    patientLeadsRepository.countLeads(filters),
    getStaffSessionFromCookies(),
  ]);

  function buildHref(page: number) {
    const params = new URLSearchParams();
    if (filters.q) params.set("q", filters.q);
    if (filters.status) params.set("status", filters.status);
    if (filters.urgency) params.set("urgency", filters.urgency);
    params.set("page", String(page));
    return `/dashboard/leads?${params.toString()}`;
  }

  function buildExportHref() {
    const params = new URLSearchParams();
    if (filters.q) params.set("q", filters.q);
    if (filters.status) params.set("status", filters.status);
    if (filters.urgency) params.set("urgency", filters.urgency);
    return `/api/export/leads?${params.toString()}`;
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Leads"
        description="Search, filter, and manage patient leads generated by Vapi and n8n."
        actions={session?.role === "ADMIN" ? <ExportCsvButton href={buildExportHref()} /> : undefined}
      />

      <LeadsFilterBar />

      <div className="overflow-hidden rounded-xl border border-border bg-card">
        {leads.length === 0 ? (
          <div className="p-6">
            <EmptyState title="No leads match your filters" description="Try adjusting your search or filters." />
          </div>
        ) : (
          <>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Patient Name</TableHead>
                  <TableHead>Phone</TableHead>
                  <TableHead>Email</TableHead>
                  <TableHead>Reason For Visit</TableHead>
                  <TableHead>Urgency</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Created At</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {leads.map((lead) => (
                  <TableRow key={lead.id}>
                    <TableCell className="font-medium">
                      <Link href={`/dashboard/leads/${lead.id}`} className="hover:text-primary">
                        {lead.patientName}
                      </Link>
                    </TableCell>
                    <TableCell className="text-muted-foreground">{lead.phone}</TableCell>
                    <TableCell className="text-muted-foreground">{lead.email ?? "—"}</TableCell>
                    <TableCell className="text-muted-foreground">{lead.reasonForVisit}</TableCell>
                    <TableCell>
                      <StatusBadge value={lead.urgency} />
                    </TableCell>
                    <TableCell>
                      <StatusBadge value={lead.status} />
                    </TableCell>
                    <TableCell className="text-muted-foreground">{lead.createdAt.toLocaleString()}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
            <Pagination page={filters.page} pageSize={filters.pageSize} totalItems={totalItems} buildHref={buildHref} />
          </>
        )}
      </div>
    </div>
  );
}
